name: muzammil_hussain
description: "My Portfolio Website"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.1
  shared_preferences: ^2.2.2
  url_strategy: ^0.2.0
  logger: ^2.0.2+1
  flutter_svg: ^2.0.10+1
  entry: ^0.0.9
  intl: ^0.19.0
  animated_flip_counter: ^0.3.2
  visibility_detector: ^0.4.0+2
  auto_size_text: ^3.0.0
  url_launcher: ^6.2.6
  delightful_toast: ^1.1.0
  go_router: ^14.1.4
  flutter_staggered_grid_view: ^0.7.0
  flutter_mailer: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0



flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/project-images/
    - assets/svg/

  fonts:
    - family: Goku
      fonts:
        - asset: assets/fonts/goku/Goku.ttf
        - asset: assets/fonts/goku/Goku Stencil.ttf
          style: italic
    - family: Raleway
      fonts:
        - asset: assets/fonts/raleway/Raleway-Black.ttf
          weight: 900
        - asset: assets/fonts/raleway/Raleway-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/raleway/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/raleway/Raleway-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/raleway/Raleway-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/raleway/Raleway-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/raleway/Raleway-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/raleway/Raleway-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/raleway/Raleway-Italic.ttf
          style: italic
        - asset: assets/fonts/raleway/Raleway-Light.ttf
          weight: 300
        - asset: assets/fonts/raleway/Raleway-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/raleway/Raleway-Medium.ttf
          weight: 500
        - asset: assets/fonts/raleway/Raleway-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/raleway/Raleway-Regular.ttf
        - asset: assets/fonts/raleway/Raleway-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/raleway/Raleway-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/raleway/Raleway-Thin.ttf
          weight: 100
        - asset: assets/fonts/raleway/Raleway-ThinItalic.ttf
          weight: 100
          style: italic
